apiVersion: v1
kind: Service
metadata:
  name: jsb3
  labels:
    run: java
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    run: java