name: build and deploy spring-api
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: unit tests
        run: mvn -B test --file pom.xml
      
#      - name: SonarQube Scan
#        uses: kitabisa/sonarqube-action@v1.2.0
#        env:
#          SONAR_SCANNER_OPTS: -X
#        with:
#          host: ${{ secrets.SONARQUBE_HOST }}
#          login: ${{ secrets.SONARQUBE_TOKEN }}
#          projectBaseDir: "src/"
#          projectKey: "my-custom-project"
        
       
      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml
          
      - name: Move built JAR to docker folder
        run: mv target/*.jar docker/spring-boot-app.jar

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: docker/Dockerfile
          push: false
          tags: vonditen1/jsb3:v1.0.0

      - name: Debug - List files
        run: ls -R

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: docker/Dockerfile
          push: true
          tags: vonditen1/jsb3:v1.0.0
